language: python
python:
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
script:
  - pip install flake8
  - flake8 niwidgets
  - pip install -qq -e '.[tests]'
  - coverage run --source=niwidgets -m pytest
  - coveralls
